services:
  database:
    image: "postgres:16-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    user: 1000:1000
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    # health check postgres ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 5s
      retries: 15
