name: Fly Deploy (Staging)
on:
  push:
    branches:
      - staging

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group-staging
    environment:
      name: staging
      url: https://tasksapp-staging.fly.dev/
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl config save --app tasksapp-staging --config fly-staging.toml
      - run: flyctl deploy --config fly-staging.toml --remote-only
